using NanoPackets.Utils;
using Riptide;

namespace NanoPackets;
public partial interface INetObject {
    public ulong Id { get; set; }

    public abstract void Serialize(Message msg);

    public abstract void Deserialize(Message msg);

    public void Serialize(Message msg, bool prefab = false) {
        msg.AddVarULong(Id);
        msg.Add(prefab ? GetType().Name : null);
        Serialize(msg);
    }

    // TODO: Autogenerated resource
    //public NetObjectResource Serialize();
}

//public partial class Ab : Node3D, INetObject {
//    public ulong Id { get; set; }
//    public Node3D Node => this.Node;

//    void INetObject.Serialize(Message msg) {
//        msg.AddVector3(Node.Rotation);
//        msg.AddVector3(Node.GlobalPosition);
//    }

//    void INetObject.Deserialize(Message msg) {
//        Node.Rotation = msg.GetVector3();
//        Node.GlobalPosition = msg.GetVector3();
//    }

//    public NetObjectResource Serialize() {
//        return new NetObjectResource();
//    }
//}